### ISSUE TITLE
1.20.1 is completely bugged

### ISSUE THREAD

**Issue by not-mlk888** [Reggarfgod/Create_Better_Motors#7]
As of: create_better_motors-3.0.1.jar for Create 6.0+
This is an amazing mod, but there are several major glitches present in the **1.20.1** version, making it mostly unplayable. Some may also be present on later versions. I am aware that some of these glitches were fixed as of later updates, but as of **1.20.1**'s latest version the glitches remain.

-The Nitro Motor, and only the Nitro Motor, at default config values, functions in intervals instead of continuously. It rotates for one cycle and briefly stops rotating, indicating its FE stored is 0 and its stress capacity is also 0.
-This may or may not be intentional, but the Reggarfonite Block is unable to be crafted, and instead is made by blasting a block of Raw Reggarfonite. Note that this is not the case with other raw ore blocks, as they are unable to be blasted. 
-The Raw Reggarfonite Block, block.create_better_motors.raw_reggarfonite_block, has no name. It also appears to be uncrushable, unlike other raw ore blocks.
-The Heavy Connector has no energy functionality, rendering it completely useless. This was fixed in 3.1.2, but the latest 1.20.1 version is still bugged.
-Reggarfonite Ore spawns above Deepslate levels, in normal stone. This was fixed in 1.21.1's first patch, so the code might be easily backport-able. Also, there is currently no config option to turn off the worldgen of Reggarfonite.
-You can't wash Crushed Raw Reggarfonite. I would suggest making it have a chance to drop Prismarine Shards, or some other item.
-Reggarfonite Ingots and Nuggets are missing the forge:ingots/reggarfonite and forge:nuggets/reggarfonite tags.

That's it for now. Please fix as much of this as you can!

**Comment by Reggarfgod** [comment]
Thank you so much for the detailed feedback! I really appreciate you taking the time to report all these issues  it’s incredibly helpful.
I’ll begin working on fixes for the 1.20.1 version as soon as possible. Some of these bugs are already resolved in newer versions, and I’ll do my best to backport those fixes where feasible. Thanks again for your support and for playing Create: Better Motors

**Comment by not-mlk888** [comment]
Thanks for the quick response! It seems that some of these issues were not properly fixed on 1.20.1. I will list all the unfixed issues, as well as a few small new ones I found.

-Reggarfonite Block is still not craftable.
-All raw ore blocks do not smelt into ore blocks, so I do not think the Raw Reggarfonite block should smelt into one as well, but this is up to personal choice.
-Up to personal choice, but the Heavy Connector should have a 2D sprite to match with Crafts & Additions' connectors.
-Deepslate Reggarfonite Ore generation cannot be turned off in configs.
-Deepslate Reggarfonite Ore should crush into the following items to be more consistent with Create's ore crushing:
2x Crushed Raw Reggarfonite 
25% 1x additional Crushed Raw Reggarfonite 
75% 1x Nugget of Experience
12% Deepslate

That's it for now. All issues not listed here are already working. Please fix as much of this as you can!

**Comment by Reggarfgod** [comment]
Okay, I’ll make sure to address these in the upcoming updates. Thank you so much for taking the time to list everything out and provide such clear feedback once again
